# Generated by Django 4.0.4 on 2022-04-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calvin_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='People',
        ),
    ]
